apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sasit-ollama-helm
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    automated:
      prune: true
      selfHeal: true
      
  source:
    chart: ollama
    repoURL: https://otwld.github.io/ollama-helm/
    targetRevision: HEAD

    # https://github.com/otwld/ollama-helm
    helm:
      valuesObject:
        fullnameOverride: ollama

        crdAnnotations:
          argocd.argoproj.io/sync-wave: "-1"
        

        ## Ollama ##
        #ollama:
        #  models:
        #    - llama2

  destination:
    server: "https://kubernetes.default.svc"
    namespace: sasit